#!/bin/bash

fruits=("apple" "banana" "orange")

# Single element (zero-indexed)
echo "${fruits[0]}"  # apple

# All elements
echo "${fruits[@]}"  # apple banana orange

# Length
echo "${#fruits[@]}"  # 3

# Add element
fruits+=("grape")

# Looping over arrays
for fruit in "${fruits[@]}"; do  # using "fruits[@]" with quotes to handle elements with spaces
	echo "I like ${fruit}"
done

