#!/bin/bash

# External command (spawns new process)
filename=$(echo "document.txt" | sed 's/.txt//')
echo ${filename}

# Parameter expansion (built-in, faster)
filename="document.txt"
echo "${filename%.txt}"

