#!/bin/bash

name="${1:?First parameter is required}"  # check first argument, if not set => use "world"
log_level="${LOG_LEVEL:-info}"  # check LOG_LEVEL, if not set => use "info"
echo "Hello, ${name} (log: ${log_level})"
