#!/bin/bash

password="secret"
echo "Length: ${#password}"  # `#password` returns the characters count of password

# validation
if [[ ${#password} -lt 8 ]]; then
	echo "Password is too short"
	exit 1
fi

