# stage 1: build
FROM ubuntu:24.04 AS builder
WORKDIR /build
COPY updater .
RUN chmod +x updater

# stage 2: runtime
FROM alpine:3.21
RUN apk add --no-cache curl ca-certificates bash
RUN addgroup -g 101 appgroup && \
	adduser -u 101 -G appgroup -D appuser
WORKDIR /app
COPY --from=builder --chown=appuser:appgroup /build/updater .
USER appuser
CMD ["./updater"]

